name: Gentx Signatures
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: gentx-validation
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: build & validate
        run: |
          git clone https://github.com/cosmos-gaminghub/nibiru
          cd nibiru
          make install
          bash -x ./scripts/generate-genesis.sh
