name: Gentx Signatures
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          bash -x ./scripts/generate-genesis.sh
